name: Test

on:
  push:
    paths:
      - "**.test.tsx"
    branches:
      - main
  pull_request:
    paths:
      - "**.test.tsx"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
