name: Test

on:
  push:
    paths:
      - 'lib/components/**/*.tsx'
    branches:
      - main
  pull_request:
    paths:
      - 'lib/components/**/*.tsx'
    branches:
      - main

jobs:
  check-test-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Check if test files exist
        run: |
          modified_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^lib/components/.*\.tsx$')

          if [ -z "$modified_files" ]; then
            echo "No modified components found, skipping tests check."
            exit 0
          fi

          missing_tests=false

          for file in $modified_files; do
            component_name=$(basename "$file" .tsx)
            test_file="tests/components/${component_name}.test.tsx"
            
            if [ ! -f "$test_file" ]; then
              echo "Error: Test file for '$file' does not exist. Please create '$test_file'."
              missing_tests=true
            else
              echo "Test file '$test_file' found for '$file'."
            fi
          done

          if [ "$missing_tests" = true ]; then
            exit 1
          fi

  run-tests:
    runs-on: ubuntu-latest
    needs: check-test-files

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
